import React, { useState, useEffect } from 'react';
import { 
  LineChart, 
  Line, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer,
  BarChart, 
  Bar, 
  Cell
} from 'recharts';
import { motion } from 'framer-motion';
import { UserProfile, WeightLog, WorkoutLog, NutritionLog } from '../types';
import { db, handleFirestoreError, OperationType } from '../lib/firebase';
import { collection, query, where, orderBy, limit, onSnapshot } from 'firebase/firestore';
import { startOfDay, format, subDays, parseISO } from 'date-fns';
import { Activity, LineChart as LineChartIcon } from 'lucide-react';

interface AnalyticsProps {
  userProfile: UserProfile;
}

export function Analytics({ userProfile }: AnalyticsProps) {
  const [weightHistory, setWeightHistory] = useState<any[]>([]);
  const [nutritionConsistency, setNutritionConsistency] = useState<any[]>([]);
  const [trainingVolume, setTrainingVolume] = useState<any[]>([]);

  useEffect(() => {
    // 1. Weight Evolution
    const weightQ = query(
      collection(db, 'weight_logs'),
      where('userId', '==', userProfile.userId),
      orderBy('date', 'asc'),
      limit(30)
    );

    const unsubscribeWeight = onSnapshot(weightQ, (snapshot) => {
      const data = snapshot.docs.map(doc => {
        const d = doc.data() as WeightLog;
        return {
          date: format(parseISO(d.date), 'MMM dd'),
          weight: d.weightKg
        };
      });
      setWeightHistory(data);
    }, (err) => handleFirestoreError(err, OperationType.LIST, 'weight_logs'));

    // 2. Nutrition & Training Consistency (Last 7 days)
    const nutritionQ = query(
      collection(db, 'nutrition_logs'),
      where('userId', '==', userProfile.userId),
      orderBy('date', 'desc'),
      limit(50)
    );

    const unsubscribeNutrition = onSnapshot(nutritionQ, (snapshot) => {
      const logs = snapshot.docs.map(doc => doc.data() as NutritionLog);
      const last7Days = Array.from({ length: 7 }).map((_, i) => {
        const date = format(subDays(new Date(), i), 'yyyy-MM-dd');
        const dayLogs = logs.filter(l => l.date === date);
        const dayCals = dayLogs.reduce((acc, curr) => acc + (curr.calories || 0), 0);
        const target = userProfile.targetDailyCalories || 2500;
        return {
          name: format(parseISO(date), 'MMM dd'),
          completed: Math.min(((dayCals || 0) / target) * 100, 100),
          target: 100
        };
      }).reverse();
      setNutritionConsistency(last7Days);
    }, (err) => handleFirestoreError(err, OperationType.LIST, 'nutrition_logs'));

    // 3. Training Volume
    const workoutQ = query(
      collection(db, 'workout_logs'),
      where('userId', '==', userProfile.userId),
      orderBy('date', 'desc'),
      limit(20)
    );

    const unsubscribeWorkout = onSnapshot(workoutQ, (snapshot) => {
      const logs = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }) as WorkoutLog);
      // Group by week or just show last 10 sessions as volume
      const volumeData = logs.slice(0, 10).map((log, i) => {
        // Workout exercises in this app have 'sets' as a number (as generated by AI)
        const totalSets = log.exercises.reduce((acc, ex: any) => acc + (Number(ex.sets) || 0), 0);
        return {
          week: format(new Date(log.date), 'MMM dd'),
          volume: totalSets * 10
        };
      }).reverse();
      setTrainingVolume(volumeData);
    }, (err) => handleFirestoreError(err, OperationType.LIST, 'workout_logs'));

    return () => {
      unsubscribeWeight();
      unsubscribeNutrition();
      unsubscribeWorkout();
    };
  }, [userProfile.userId]);

  const consistencyData = [
    { name: 'Nutrition', completed: nutritionConsistency.length > 0 ? Math.round(nutritionConsistency.reduce((a, b) => a + (b.completed || 0), 0) / 7) : 0, target: 100 },
    { name: 'Training', completed: trainingVolume.length > 0 ? 80 : 0, target: 100 },
    { name: 'Recovery', completed: 75, target: 100 }
  ];

  return (
    <div className="space-y-10 animate-in fade-in duration-1000 pb-20">
      <header className="px-6 space-y-2">
        <div className="flex items-center gap-3 opacity-60">
           <div className="w-8 h-px wine-gradient rounded-full"></div>
           <p className="text-forge-gray font-black uppercase tracking-[0.4em] text-[10px] italic">Strategic Intelligence</p>
        </div>
        <h2 className="text-3xl font-black text-white tracking-tighter uppercase italic glow-text-white">Neural Analytics</h2>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Weight Evolution */}
        <div className="glass-panel p-8 rounded-[2rem] shadow-2xl relative overflow-hidden group border-white/5">
          <div className="absolute top-0 right-0 w-32 h-32 bg-forge-wine/5 blur-3xl rounded-full -z-10 group-hover:bg-forge-wine/10 transition-all"></div>
          <div className="flex justify-between items-center mb-10 px-2">
            <h3 className="text-[10px] font-black text-white tracking-[0.4em] uppercase italic glow-text-white">Biometric Trajectory</h3>
            <div className="px-3 py-1 glass-panel border-forge-wine/20 rounded-lg text-[8px] font-black text-forge-wine-light uppercase tracking-widest glow-border">Live Stream</div>
          </div>
          <div className="h-[280px] relative z-10">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={weightHistory}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)" vertical={false} />
                <XAxis dataKey="date" stroke="rgba(255,255,255,0.4)" fontSize={10} tickLine={false} axisLine={false} dy={10} />
                <YAxis stroke="rgba(255,255,255,0.4)" fontSize={10} tickLine={false} axisLine={false} domain={['dataMin - 5', 'dataMax + 5']} dx={-10} />
                <Tooltip 
                  contentStyle={{ backgroundColor: 'rgba(13,13,13,0.95)', border: '1px solid rgba(196, 30, 58, 0.5)', borderRadius: '16px', fontSize: '10px', boxShadow: '0 10px 30px rgba(0,0,0,0.8)', color: '#fff', backdropFilter: 'blur(10px)' }}
                  itemStyle={{ color: '#fff', fontWeight: 'bold' }}
                  cursor={{ stroke: 'rgba(196, 30, 58, 0.5)', strokeWidth: 1 }}
                />
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" vertical={false} />
                <Line 
                  type="monotone" 
                  dataKey="weight" 
                  stroke="#C41E3A" 
                  strokeWidth={4} 
                  dot={{ fill: '#C41E3A', r: 5, strokeWidth: 2, stroke: 'rgba(255,255,255,0.8)' }} 
                  activeDot={{ r: 8, stroke: '#C41E3A', strokeWidth: 4, fill: '#fff', className: "animate-pulse" }} 
                />
              </LineChart>
            </ResponsiveContainer>
            {weightHistory.length === 0 && (
              <div className="absolute inset-0 flex flex-col items-center justify-center space-y-3">
                <div className="w-12 h-12 rounded-full bg-white/5 flex items-center justify-center">
                  <LineChartIcon size={20} className="text-forge-gray opacity-20" />
                </div>
                <p className="text-[10px] font-black text-forge-gray uppercase tracking-[0.3em] opacity-40 italic">Awaiting Biometric Data</p>
                <p className="text-[9px] text-forge-gray opacity-20 max-w-[180px] text-center uppercase tracking-widest leading-relaxed">Update your weight in profile to initialize tracking.</p>
              </div>
            )}
          </div>
        </div>

        {/* Training Load */}
        <div className="glass-panel p-8 rounded-[2rem] shadow-2xl relative overflow-hidden group border-white/5">
          <div className="absolute bottom-0 left-0 w-32 h-32 bg-forge-wine/5 blur-3xl rounded-full -z-10 group-hover:bg-forge-wine/10 transition-all"></div>
          <div className="flex justify-between items-center mb-10 px-2">
            <h3 className="text-[10px] font-black text-white tracking-[0.4em] uppercase italic glow-text-white">Mechanical Output</h3>
            <div className="px-3 py-1 glass-panel border-white/5 rounded-lg text-[8px] font-black text-forge-gray uppercase tracking-widest">Archive 01</div>
          </div>
          <div className="h-[280px] relative z-10">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={trainingVolume}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)" vertical={false} />
                <XAxis dataKey="week" stroke="rgba(255,255,255,0.4)" fontSize={10} tickLine={false} axisLine={false} dy={10} />
                <YAxis stroke="rgba(255,255,255,0.4)" fontSize={10} tickLine={false} axisLine={false} dx={-10} />
                <Tooltip 
                  cursor={{ fill: 'rgba(196, 30, 58, 0.05)' }}
                  contentStyle={{ backgroundColor: 'rgba(13,13,13,0.95)', border: '1px solid rgba(196, 30, 58, 0.5)', borderRadius: '16px', fontSize: '10px', boxShadow: '0 10px 30px rgba(0,0,0,0.8)', color: '#fff', backdropFilter: 'blur(10px)' }}
                  itemStyle={{ color: '#C41E3A', fontWeight: 'bold' }}
                />
                <Bar 
                    dataKey="volume" 
                    radius={[10, 10, 0, 0]} 
                    className="transition-all duration-300"
                >
                  {trainingVolume.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={index % 2 === 0 ? "url(#wineGradient)" : "rgba(196, 30, 58, 0.3)"} />
                  ))}
                </Bar>
                <defs>
                   <linearGradient id="wineGradient" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor="#C41E3A" />
                      <stop offset="100%" stopColor="#7A1128" />
                   </linearGradient>
                </defs>
              </BarChart>
            </ResponsiveContainer>
            {trainingVolume.length === 0 && (
              <div className="absolute inset-0 flex flex-col items-center justify-center space-y-3">
                <div className="w-12 h-12 rounded-full bg-white/5 flex items-center justify-center">
                  <Activity size={20} className="text-forge-gray opacity-20" />
                </div>
                <p className="text-[10px] font-black text-forge-gray uppercase tracking-[0.3em] opacity-40 italic">Awaiting Mechanical Data</p>
                <p className="text-[9px] text-forge-gray opacity-20 max-w-[180px] text-center uppercase tracking-widest leading-relaxed">Complete workout sessions to quantify output.</p>
              </div>
            )}
          </div>
        </div>

        {/* Precision Index */}
        <div className="lg:col-span-2 glass-panel p-10 rounded-[2.5rem] shadow-2xl relative overflow-hidden group border-white/5">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[60%] h-[60%] bg-forge-wine/5 blur-[100px] rounded-full -z-10 group-hover:bg-forge-wine/10 transition-all"></div>
          <div className="flex justify-between items-center mb-10 px-4">
             <div className="space-y-1">
                <h3 className="text-[10px] font-black text-white tracking-[0.6em] uppercase italic glow-text-white">Tactical Alignment Index</h3>
                <p className="text-forge-gray text-[9px] font-black uppercase tracking-[0.3em] opacity-40 italic">Systemic Protocol Compliance</p>
             </div>
             <div className="flex gap-3">
                <div className="w-2 h-2 rounded-full wine-gradient glow-border"></div>
                <div className="w-2 h-2 rounded-full bg-white/10"></div>
             </div>
          </div>
          <div className="h-[300px] relative z-10">
             <ResponsiveContainer width="100%" height="100%">
              <BarChart layout="vertical" data={consistencyData} margin={{ left: 20 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)" horizontal={false} />
                <XAxis type="number" stroke="rgba(255,255,255,0.2)" fontSize={10} tickLine={false} axisLine={false} dy={10} />
                <YAxis dataKey="name" type="category" stroke="rgba(255,255,255,0.6)" fontSize={11} fontWeight="900" tickLine={false} axisLine={false} width={140} className="italic uppercase tracking-[0.2em]" />
                <Tooltip 
                  cursor={{ fill: 'rgba(255,255,255,0.03)' }}
                  contentStyle={{ backgroundColor: 'rgba(13,13,13,0.9)', border: '1px solid rgba(196, 30, 58, 0.4)', borderRadius: '16px', fontSize: '10px', boxShadow: '0 10px 30px rgba(0,0,0,0.5)', color: '#fff', backdropFilter: 'blur(10px)' }}
                  itemStyle={{ color: '#C41E3A', fontWeight: 'bold' }}
                />
                <Bar dataKey="completed" radius={[0, 15, 15, 0]} barSize={32}>
                  {consistencyData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.completed > 90 ? "#C41E3A" : entry.completed > 80 ? "rgba(196, 30, 58, 0.6)" : "rgba(196, 30, 58, 0.2)"} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
    </div>
  );
}
